name: "CI: compile doc"

on: pull_request
jobs:
    doc:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: prefix-dev/setup-pixi@v0.8.1
            - name: compile doc
              run: pixi run doc
